name: nets

channels:
  - default
  - conda-forge

dependencies:
  - python>=3.11
  - ipython
  - ipykernel
  - pre-commit

  - numpy
  - pandas>=2.0
  - pytables
  - submitit

  # JAX:
  - conda-forge::jax

  - pip
  - pip:
      - -e .
